// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function DataList(props) {
  return React.createElement("div", {
              className: "container"
            }, React.createElement("h3", undefined, "Data Go Here"));
}

var make = DataList;

exports.make = make;
/* react Not a pure module */
