// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function DataList(Props) {
  return React.createElement("div", undefined, React.createElement("h3", undefined, "Data Go Here"));
}

var make = DataList;

exports.make = make;
/* react Not a pure module */
