// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Js_exn = require("rescript/lib/js/js_exn.js");
var DataList = require("./components/DataList.bs.js");
var Client = require("react-dom/client");

console.log("Hello, ReScript");

var container = document.querySelector("#app");

var root = Client.createRoot((container == null) ? Js_exn.raiseError("Could not find root element") : container);

root.render(React.createElement(DataList.make, {}));

exports.root = root;
/*  Not a pure module */
